name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build_release:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Cache gradle build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-${{ github.sha }}
          restore-keys: gradle-builds
      - name: Build with Gradle
        env:
          REL_KEY: ${{ secrets.REL_KEY }}
#          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          bash ./gradlew assembleRelease assembleDebug
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: snapshot
          path: |
            ${{ github.workspace }}/app/build/outputs/apk
#            ${{ github.workspace }}/app/build/outputs/mapping
